global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rule-engine'
    static_configs:
      - targets: ['rule-engine:9091']
  - job_name: 'data-simulator'
    static_configs:
      - targets: ['data-simulator:9092']
  - job_name: 'iot-controller'
    static_configs:
      - targets: ['iot-controller:5555']